on:
  workflow_dispatch:

jobs:
  plop:
    runs-on: ubuntu-latest
    steps:
      - name: Foo
        run: |
          gh pr comment 3 --body "hello"
        env:
          GH_TOKEN: ${{ github.token }}
